### ISSUE TITLE
Broken modules when building

### ISSUE THREAD

**Issue by iddrew** [kaltura/kmc-ng#199]
Hi,

I am running this on centos 6.9 with the latest nodejs and yarn, however when trying to install your latest master with yarn it breaks completaly and fails to compile.

Below are the errors i get:

[root@k13-andrew kmc-ng]# yarn start
yarn start v0.27.5
$ ng serve --host=0.0.0.0 --disable-host-check
WARNING Running a server with --disable-host-check is a security risk. See https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a for more information.
** NG Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200 **
Hash: 56a726a90d2fe295f3f4                                                                 
Time: 42204ms
chunk    {0} 0.chunk.js, 0.chunk.js.map 1.44 MB {1} {2} {3} {4} {6} [rendered]
chunk    {1} 1.chunk.js, 1.chunk.js.map 337 kB {0} {2} {3} {4} {6} [rendered]
chunk    {2} 2.chunk.js, 2.chunk.js.map 166 kB {0} {1} {3} {4} {6} [rendered]
chunk    {3} 3.chunk.js, 3.chunk.js.map 72.7 kB {0} {1} {2} {4} {6} [rendered]
chunk    {4} 4.chunk.js, 4.chunk.js.map 12.1 kB {0} {1} {2} {3} {6} [rendered]
chunk    {5} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 479 kB {9} [initial] [rendered]
chunk    {6} main.bundle.js, main.bundle.js.map (main) 139 kB {8} [initial] [rendered]
chunk    {7} styles.bundle.js, styles.bundle.js.map (styles) 8.49 kB {9} [initial] [rendered]
chunk    {8} vendor.bundle.js, vendor.bundle.js.map (vendor) 6.2 MB [initial] [rendered]
chunk    {9} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in ./src/app/components/upload/upload-menu/upload-menu.component.scss
Module build failed: 
        background-color: $kOrange;
                         ^
      Undefined variable: "$kOrange".
      in /root/test2/kmc-ng/src/app/components/upload/upload-menu/upload-menu.component.scss (line 35, column 27)
 @ ./src/app/components/upload/upload-menu/upload-menu.component.ts 12:17-56
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./src/applications/content-entries-app/entries/entries-list.component.scss
Module build failed: 
    background: $kMagnifyingGlassBkg;
               ^
      Undefined variable: "$kMagnifyingGlassBkg".
      in /root/test2/kmc-ng/src/applications/content-entries-app/entries/entries-list.component.scss (line 84, column 17)
 @ ./src/applications/content-entries-app/entries/entries-list.component.ts 165:17-57
 @ ./src/applications/content-entries-app/content-entries-app.routes.ts
 @ ./src/applications/content-entries-app/content-entries-app.module.ts
 @ ./src async
 @ ./~/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./src/applications/content-playlists-app/playlists/playlists-list.component.scss
Module build failed: 
		background: $kMagnifyingGlassBkg;
             ^
      Undefined variable: "$kMagnifyingGlassBkg".
      in /root/test2/kmc-ng/src/applications/content-playlists-app/playlists/playlists-list.component.scss (line 87, column 15)
 @ ./src/applications/content-playlists-app/playlists/playlists-list.component.ts 271:17-59
 @ ./src/applications/content-playlists-app/content-playlists-app.routes.ts
 @ ./src/applications/content-playlists-app/content-playlists-app.module.ts
 @ ./src async
 @ ./~/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./src/applications/content-categories-app/categories/categories-list.component.scss
Module build failed: 
    background: $kMagnifyingGlassBkg;
               ^
      Undefined variable: "$kMagnifyingGlassBkg".
      in /root/test2/kmc-ng/src/applications/content-categories-app/categories/categories-list.component.scss (line 83, column 17)
 @ ./src/applications/content-categories-app/categories/categories-list.component.ts 82:17-60
 @ ./src/applications/content-categories-app/content-categories-app.routes.ts
 @ ./src/applications/content-categories-app/content-categories-app.module.ts
 @ ./src async
 @ ./~/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./~/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":["/root/test2/kmc-ng/src/styles"]}!./src/styles/app-theme/styles.scss
Module build failed: 
        color: $inputGroupTextColor;
              ^
      Undefined variable: "$inputGroupTextColor".
      in /root/test2/kmc-ng/node_modules/primeng/resources/themes/_theme.scss (line 153, column 16)
 @ ./src/styles/app-theme/styles.scss 4:14-207
 @ multi ./src/styles/app-theme/styles.scss
webpack: Failed to compile.

Can you please update the master branch to compile correctly?

Thanks and nice work :)

**Comment by kaltura-hooks** [comment]
Hi @iddrew,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by esakal** [comment]
Hello @iddrew,
thanks for reaching out.

The KMC-ng project is built out of multiple repositories. Since we develop our features across all of them to be able to run our latest code you need to setup a workspace as described in the [readme.md file - Get the sources Option II](https://github.com/kaltura/kmc-ng#option-ii-the-red-pill--develop-kmc-ng-complete-solution-multiple-repos). The setup is quite fast and automatic but it is a bit more complex because it connect libraries locally.

Since we encountered some developers that wanted to build & run KMC-ng repo only without setup the complete solution, we added support for that as described in the [readme.md file - Get the sources Option I](https://github.com/kaltura/kmc-ng#option-i-the-blue-pill---develop-kmc-ng-application). Note that while running Option I is easier you will not see the latest bytes of code.

Have you tried one of those options? Which one? 

Eran.

**Comment by esakal** [comment]
I'm closing this issue as no response was retrieved for a while now
