### ISSUE TITLE
Trying to use kmc-ng against a self hosted kaltura ce server

### ISSUE THREAD

**Issue by danionescu2007** [kaltura/kmc-ng#310]
I already tried configuring in environment.ts:
```
export const environment = {
  production: true,
  "core": {
    "kaltura": {
      "apiUrl" : "http://kaltura.streamhub1.go.ro/api_v3/index.php",
      "cdnUrl": "http://kaltura.streamhub1.go.ro",
      "kmcUrl": "kaltura.streamhub1.go.ro:81",
      "expiry": "86400",
      "privileges": "disableentitlement",
      "previewUIConf": "38524931",
      "liveAnalyticsVersion": "v2.6",
      "contactsalesforce": "https://streamhub.ro/#contact"
    }
  }
}
```
After that I ran `npm install`, then `npm start` to start the server, but it still points to the central kaltura.com server.

**Comment by kaltura-hooks** [comment]
Hi @danionescu2007,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by esakal** [comment]
Hi @danionescu2007,
We are not using environment.ts for a while now. did you try settings it in the configuration file [here](https://github.com/kaltura/kmc-ng/blob/master/src/app-config/index.ts#L13)?

Eran.

**Comment by esakal** [comment]
@danionescu2007,
I updated the readme.md file with the right instructions [here](https://github.com/kaltura/kmc-ng#configuring-the-application-endpoints) please take a look and let me know if works for you now

**Comment by esakal** [comment]
I'm closing this issue. If it still relevant please reply or create a new issue.
