### ISSUE TITLE
kmc-ng browse error

### ISSUE THREAD

**Issue by BandaruAmruthaValli** [kaltura/kmc-ng#336]
I am following the guide in the readme to set-up the kmc-ng on a windows.  I am getting an error in browser console  
onerrorLogger: {"msg":"Uncaught Exception","errorMsg":{"isTrusted":true}}

Appreciate your support.

**Comment by kaltura-hooks** [comment]
Hi @BandaruAmruthaValli,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by esakal** [comment]
Hello @BandaruAmruthaValli,

Can you please retry with the new version we deployed v3.4.1?

If it still happens, we added a logger infrastructure that has undesired behavior to hide runtime errors and show instead the error you reported. We will bypass this behavior shortly, in the meanwhile please send the actual error so we will be able to assist. To get the actual error click on the following link
![image](https://user-images.githubusercontent.com/4751797/34917203-f3949b94-f94b-11e7-8f9b-325c794ab581.png)

Add a breakpoint as shown below and once you reached that point check the content of `errorMsg` argument.
![image](https://user-images.githubusercontent.com/4751797/34917215-16ef7438-f94c-11e7-8d53-0c672982fdeb.png)

Eran.

**Comment by esakal** [comment]
I'm closing this issue for housekeeping. If this error still happens please open a new issue.
