### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by ifeatu** [kaltura/kmc-ng#809]
ERROR in ./src/kmc-app/components/app-menu/app-menu.component.scss
(Emitted value instead of an instance of Error) CssSyntaxError: /root/kaltura/kmc-ng/src/kmc-app/styles/scss/_kmc-logo.scss:9:16: Can't resolve '../../styles/assets/beta.svg' in '/root/kaltura/kmc-ng/src/kmc-app/components/app-menu'

   7 | }
   8 | .k-beta-logo {
>  9 |     background: url('../../styles/assets/beta.svg') no-repeat left center;
     |                ^
  10 |     display:inline-block;
  11 | }

ERROR in ./src/kmc-app/components/login/login.component.scss
(Emitted value instead of an instance of Error) CssSyntaxError: /root/kaltura/kmc-ng/src/kmc-app/styles/scss/_kmc-logo.scss:9:16: Can't resolve '../../styles/assets/beta.svg' in '/root/kaltura/kmc-ng/src/kmc-app/components/login'

   7 | }
   8 | .k-beta-logo {
>  9 |     background: url('../../styles/assets/beta.svg') no-repeat left center;
     |                ^
  10 |     display:inline-block;
  11 | }

ℹ ｢wdm｣: Failed to compile.

**Comment by kaltura-hooks** [comment]
Hi @ifeatu,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by amirch1** [comment]
Hi @ifeatu , Thanks for the input.
Indeed seems that the beta.svg file name is capitalized. Pending your sass compiler version, this might cause the reported compilation error. We will fix this in our next version. For now, simply rename the file Beta.svg to beta.svg
