### ISSUE TITLE
Filter state is lost when accessing entry analytics

### ISSUE THREAD

**Issue by jbrule** [kaltura/kmc-ng#914]
The state of filters in the KMC is lost after viewing entry analytics.

How to duplicate

1. Enter KMC and be on Entries list screen
2. Create a filter of using **search**, **Filter Categories** and/or **Refine**
3. Click on Entry.
4. Click on **View Analytics**
5. Click back arrow to go back to entry.
6. Click back arrow to go back to entry list.
7. Entries are no longer filtered.

We are Saas users.

**Comment by kaltura-hooks** [comment]
Hi @jbrule,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by amirch1** [comment]
@jbrule - thanks for your input. Unfortunately this is a limitation as filters state is not saved across different modules of the KMC application (not just Analytics).
