### ISSUE TITLE
We have a Community Edition 11.21.0-2 installed to deb based Linux dist, Need help to upgrade it.

### ISSUE THREAD

**Issue by nirojshrestha019** [kaltura/kmc-ng#964]
I did try to upgrade following the instruction from https://github.com/kaltura/platform-install-packages/blob/Lynx-12.0.0/doc/install-kaltura-deb-based.md#upgrade-kaltura . I am a Sudo user but still am getting the following errors while running this upgrade command: 
`aptitude install ~Nkaltura `

I am a bit lost seeing the following errors.
## Error
```
dpkg: error processing package kaltura-batch (--configure):
 subprocess installed post-installation script returned error exit status 11
dpkg: dependency problems prevent configuration of kaltura-server:
 kaltura-server depends on kaltura-batch; however:
  Package kaltura-batch is not configured yet.
 kaltura-server depends on kaltura-sphinx; however:
  Package kaltura-sphinx is not configured yet.

dpkg: error processing package kaltura-server (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.19-0ubuntu6.15) ...
Errors were encountered while processing:
 kaltura-sphinx
 kaltura-batch
 kaltura-server
```

Additionally here is the error log from kaltura_batch.log:
```
2021-10-02 20:19:49 [0.000000] [957244127] [1] [BATCH] [KSchedulerConfig->load] NOTICE: loading configuration /opt/kaltura/app/configurations/batch at 1633216673
PHP Fatal error: Uncaught exception 'Zend_Config_Exception' with message 'Section 'ip-10-155-123-20' cannot be found in /opt/kaltura/app/cache//batch/config.ini' in /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php:150
Stack trace:
#0 /opt/kaltura/app/batch/scheduler/KSchedulerConfig.class.php(59): Zend_Config_Ini->__construct('/opt/kaltura/ap...', 'ip-10-155-123-2...', true)
#1 /opt/kaltura/app/batch/scheduler/KSchedulerConfig.class.php(42): KSchedulerConfig->load()
#2 /opt/kaltura/app/batch/scheduler/KGenericScheduler.class.php(88): KSchedulerConfig->__construct('/opt/kaltura/ap...')
#3 /opt/kaltura/app/batch/scheduler/KGenericScheduler.class.php(70): KGenericScheduler->loadConfig('/opt/kaltura/ap...')
#4 /opt/kaltura/app/batch/KGenericBatchMgr.class.php(37): KGenericScheduler->__construct('/usr/bin/php', '/opt/kaltura/ap...')
#5 {main}
thrown in /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php on line 150
```

Additionally, I followed the following FAQ (http://kaltura.github.io/platform-install-packages/)
* * I've installed Kaltura. How can I tell if there are any errors?
  * You can use the following tail and grep combination to monitor the logs for errors:
tail -f /opt/kaltura/log/*.log | grep "ERR:\|PHP\|trace\|CRIT" --color=always

and ran the following command to get some errors:
`tail -f /opt/kaltura/log/*.log | grep "ERR:\|PHP\|trace\|CRIT" --color=always`

Error:
```
PHP Fatal error:  Uncaught exception 'Zend_Config_Exception' with message 'Section 'ip-10-165-81-123' cannot be found in /opt/kaltura/app/cache//batch/config.ini' in /opt/kaltura/app/vendor/ZendFramework/library/Zend/Config/Ini.php:150
Stack trace:
Stack trace:
Stack trace:
```

Also is there a way to integrate the current Kaltura server Community Edition 11.21.0-2 to KMCng (https://github.com/kaltura/kmc-ng) to replace the legacy KMC flash-based application? I am new to this and could not find a proper resource, so Could you please provide me a direction to do that if possible? 

If this upgrade fails then can we at least do a fresh installation of Kaltura CE 16.14.0 and migrate the database of the current Kaltura Community Edition 11.21.0-2 to the new instance?

Thank you.

**Comment by kaltura-hooks** [comment]
Hi @nirojshrestha019,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by amirch1** [comment]
@jessp01 - can you please take a look?

**Comment by nirojshrestha019** [comment]
any updates on this thread?

**Comment by nirojshrestha019** [comment]
very poor support from the team. Closing this ticket because there was no response.
